from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
SKILLS_DIR = REPO_ROOT / "skills"
TEMPLATES_DIR = REPO_ROOT / "templates"


def load_manifest() -> dict:
    manifest_path = SKILLS_DIR / "manifest.json"
    return json.loads(manifest_path.read_text(encoding="utf-8"))


def cmd_list_skills(_: argparse.Namespace) -> int:
    manifest = load_manifest()
    for skill in manifest["skills"]:
        print(f"{skill['name']}: {skill['purpose']}")
    return 0


def cmd_init(args: argparse.Namespace) -> int:
    target = Path(args.path).resolve()
    target.mkdir(parents=True, exist_ok=True)

    out_skills = target / "skills"
    out_templates = target / "templates"
    out_skills.mkdir(exist_ok=True)
    out_templates.mkdir(exist_ok=True)

    manifest = load_manifest()
    selected = set(args.skills or [])
    if not selected:
        selected = {skill["name"] for skill in manifest["skills"]}

    copied = []
    for skill in manifest["skills"]:
        if skill["name"] not in selected:
            continue
        src = SKILLS_DIR / skill["path"]
        dst_dir = out_skills / skill["name"]
        dst_dir.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dst_dir / "SKILL.md")
        copied.append(skill["name"])

    for template in TEMPLATES_DIR.glob("*.md"):
        shutil.copy2(template, out_templates / template.name)

    readme = target / "README.md"
    if not readme.exists():
        readme.write_text(
            "# ML Researcher Workspace\n\n"
            "Generated by `mlro init`.\n\n"
            "## Installed skills\n\n"
            + "\n".join(f"- {name}" for name in copied)
            + "\n",
            encoding="utf-8",
        )

    print(f"Initialized {target}")
    print(f"Installed skills: {', '.join(copied)}")
    return 0


def cmd_extract_claims(args: argparse.Namespace) -> int:
    text = Path(args.input).read_text(encoding="utf-8")
    lower = text.lower()

    lines = [line.strip() for line in text.splitlines() if line.strip()]
    candidate_claims = [
        line
        for line in lines
        if any(word in line.lower() for word in ["improve", "outperform", "achieve", "reduce", "increase"])
    ]

    limitations = [
        line
        for line in lines
        if any(word in line.lower() for word in ["limitation", "future work", "do not", "not evaluate", "missing"])
    ]

    metrics = []
    for metric in ["accuracy", "f1", "auc", "loss", "bleu", "rouge", "precision", "recall"]:
        if metric in lower:
            metrics.append(metric)

    output = [
        "# Claim Extraction Draft",
        "",
        "## Core claim",
        candidate_claims[0] if candidate_claims else "not specified",
        "",
        "## Evidence table",
        "",
        "| Claim | Evidence in text | Evidence type | Confidence | Reproduction note |",
        "| --- | --- | --- | --- | --- |",
    ]

    if candidate_claims:
        for claim in candidate_claims:
            output.append(f"| {claim} | Reported in input text | author_claim | medium | Needs independent reproduction. |")
    else:
        output.append("| not specified | missing | missing | low | Need a clearer claim. |")

    output.extend(
        [
            "",
            "## Metrics",
            ", ".join(sorted(set(metrics))) if metrics else "not specified",
            "",
            "## Limitations",
        ]
    )
    if limitations:
        output.extend(f"- {line}" for line in limitations)
    else:
        output.append("- not specified")

    output.extend(
        [
            "",
            "## Questions before reproduction",
            "- What dataset and split should be used?",
            "- What baseline implementation should be matched?",
            "- What seed policy is required?",
            "",
            "Ready to plan experiments: partial",
        ]
    )

    result = "\n".join(output) + "\n"
    if args.output:
        Path(args.output).write_text(result, encoding="utf-8")
        print(f"Wrote {args.output}")
    else:
        print(result)
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="mlro")
    subparsers = parser.add_subparsers(dest="command", required=True)

    list_parser = subparsers.add_parser("list-skills", help="List available ML research skills")
    list_parser.set_defaults(func=cmd_list_skills)

    init_parser = subparsers.add_parser("init", help="Initialize a research workspace")
    init_parser.add_argument("path", nargs="?", default="ml-researcher-workspace")
    init_parser.add_argument("--skills", nargs="*", help="Optional skill names to install")
    init_parser.set_defaults(func=cmd_init)

    extract_parser = subparsers.add_parser("extract-claims", help="Extract a first-pass claim brief from text")
    extract_parser.add_argument("input", help="Markdown or text file")
    extract_parser.add_argument("--output", "-o", help="Write output to a file")
    extract_parser.set_defaults(func=cmd_extract_claims)

    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())

