from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path

try:
    from ml_researcher_os.repo_doctor import doctor_repo, render_doctor_markdown
    from ml_researcher_os.research_loop import (
        init_loop,
        load_loop,
        program_path,
        record_run,
        render_program,
        render_report,
        report_path,
    )
    from ml_researcher_os.self_improve import (
        audit_pack,
        improvement_backlog,
        load_failure_file,
        record_failure,
        render_backlog,
        render_failure_issue,
        write_regression_task,
        write_json,
    )
except ModuleNotFoundError:  # Allows direct execution via python src/ml_researcher_os/cli.py
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
    from ml_researcher_os.repo_doctor import doctor_repo, render_doctor_markdown
    from ml_researcher_os.research_loop import (
        init_loop,
        load_loop,
        program_path,
        record_run,
        render_program,
        render_report,
        report_path,
    )
    from ml_researcher_os.self_improve import (
        audit_pack,
        improvement_backlog,
        load_failure_file,
        record_failure,
        render_backlog,
        render_failure_issue,
        write_regression_task,
        write_json,
    )


REPO_ROOT = Path(__file__).resolve().parents[2]
SKILLS_DIR = REPO_ROOT / "skills"
TEMPLATES_DIR = REPO_ROOT / "templates"


def load_manifest() -> dict:
    manifest_path = SKILLS_DIR / "manifest.json"
    return json.loads(manifest_path.read_text(encoding="utf-8"))


def cmd_list_skills(_: argparse.Namespace) -> int:
    manifest = load_manifest()
    for skill in manifest["skills"]:
        print(f"{skill['name']}: {skill['purpose']}")
    return 0


def cmd_init(args: argparse.Namespace) -> int:
    target = Path(args.path).resolve()
    target.mkdir(parents=True, exist_ok=True)

    out_skills = target / "skills"
    out_templates = target / "templates"
    out_skills.mkdir(exist_ok=True)
    out_templates.mkdir(exist_ok=True)

    manifest = load_manifest()
    selected = set(args.skills or [])
    if not selected:
        selected = {skill["name"] for skill in manifest["skills"]}

    copied = []
    for skill in manifest["skills"]:
        if skill["name"] not in selected:
            continue
        src = SKILLS_DIR / skill["path"]
        dst_dir = out_skills / skill["name"]
        dst_dir.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dst_dir / "SKILL.md")
        copied.append(skill["name"])

    for template in TEMPLATES_DIR.glob("*.md"):
        shutil.copy2(template, out_templates / template.name)

    readme = target / "README.md"
    if not readme.exists():
        readme.write_text(
            "# ML Researcher Workspace\n\n"
            "Generated by `mlro init`.\n\n"
            "## Installed skills\n\n"
            + "\n".join(f"- {name}" for name in copied)
            + "\n",
            encoding="utf-8",
        )

    print(f"Initialized {target}")
    print(f"Installed skills: {', '.join(copied)}")
    return 0


def cmd_extract_claims(args: argparse.Namespace) -> int:
    text = Path(args.input).read_text(encoding="utf-8")
    lower = text.lower()

    lines = [line.strip() for line in text.splitlines() if line.strip()]
    candidate_claims = [
        line
        for line in lines
        if any(word in line.lower() for word in ["improve", "outperform", "achieve", "reduce", "increase"])
    ]

    limitations = [
        line
        for line in lines
        if any(word in line.lower() for word in ["limitation", "future work", "do not", "not evaluate", "missing"])
    ]

    metrics = []
    for metric in ["accuracy", "f1", "auc", "loss", "bleu", "rouge", "precision", "recall"]:
        if metric in lower:
            metrics.append(metric)

    output = [
        "# Claim Extraction Draft",
        "",
        "## Core claim",
        candidate_claims[0] if candidate_claims else "not specified",
        "",
        "## Evidence table",
        "",
        "| Claim | Evidence in text | Evidence type | Confidence | Reproduction note |",
        "| --- | --- | --- | --- | --- |",
    ]

    if candidate_claims:
        for claim in candidate_claims:
            output.append(f"| {claim} | Reported in input text | author_claim | medium | Needs independent reproduction. |")
    else:
        output.append("| not specified | missing | missing | low | Need a clearer claim. |")

    output.extend(
        [
            "",
            "## Metrics",
            ", ".join(sorted(set(metrics))) if metrics else "not specified",
            "",
            "## Limitations",
        ]
    )
    if limitations:
        output.extend(f"- {line}" for line in limitations)
    else:
        output.append("- not specified")

    output.extend(
        [
            "",
            "## Questions before reproduction",
            "- What dataset and split should be used?",
            "- What baseline implementation should be matched?",
            "- What seed policy is required?",
            "",
            "Ready to plan experiments: partial",
        ]
    )

    result = "\n".join(output) + "\n"
    if args.output:
        Path(args.output).write_text(result, encoding="utf-8")
        print(f"Wrote {args.output}")
    else:
        print(result)
    return 0


def cmd_audit(args: argparse.Namespace) -> int:
    result = audit_pack(REPO_ROOT)
    payload = {"ok": result.ok, "score": result.score, "checks": result.checks}
    if args.json:
        print(json.dumps(payload, indent=2))
    else:
        print(f"Self-audit score: {result.score}/100")
        for check in result.checks:
            marker = "PASS" if check["ok"] else "FAIL"
            print(f"{marker} {check['name']} - {check['detail']}")
    return 0 if result.ok else 1


def cmd_doctor(args: argparse.Namespace) -> int:
    report = doctor_repo(Path(args.path))
    markdown = render_doctor_markdown(report)

    if args.json_output:
        write_json(Path(args.json_output), report)
        print(f"Wrote {args.json_output}")

    if args.output:
        Path(args.output).write_text(markdown, encoding="utf-8")
        print(f"Wrote {args.output}")

    if args.json:
        print(json.dumps(report, indent=2))
    elif not args.output:
        print(markdown)

    return 0 if report["score"] >= args.min_score else 1


def cmd_record_failure(args: argparse.Namespace) -> int:
    path = record_failure(
        repo_root=REPO_ROOT,
        title=args.title,
        observed=args.observed,
        expected=args.expected,
        skill=args.skill,
        severity=args.severity,
        tags=args.tag or [],
        evidence=args.evidence,
    )
    print(f"Recorded failure: {path}")
    return 0


def cmd_issue_from_failure(args: argparse.Namespace) -> int:
    failure = load_failure_file(Path(args.failure))
    body = render_failure_issue(failure)
    if args.output:
        Path(args.output).write_text(body, encoding="utf-8")
        print(f"Wrote {args.output}")
    else:
        print(body)
    return 0


def cmd_make_regression(args: argparse.Namespace) -> int:
    failure = load_failure_file(Path(args.failure))
    try:
        target = write_regression_task(failure, Path(args.output_dir), force=args.force)
    except FileExistsError as exc:
        print(f"Regression task already exists: {exc}", file=sys.stderr)
        print("Use --force to overwrite the task skeleton.", file=sys.stderr)
        return 2
    print(f"Wrote regression task: {target}")
    return 0


def cmd_loop_init(args: argparse.Namespace) -> int:
    try:
        init_loop(
            workspace=Path(args.path),
            metric=args.metric,
            direction=args.direction,
            budget_minutes=args.budget_minutes,
            goal=args.goal,
            command=args.command,
            force=args.force,
        )
    except FileExistsError as exc:
        print(f"Loop ledger already exists: {exc}", file=sys.stderr)
        print("Use --force to overwrite the loop skeleton.", file=sys.stderr)
        return 2
    print(f"Initialized research loop: {Path(args.path).resolve() / '.mlro' / 'research-loop.json'}")
    print(f"Wrote program: {program_path(Path(args.path))}")
    print(f"Wrote report: {report_path(Path(args.path))}")
    return 0


def cmd_loop_record(args: argparse.Namespace) -> int:
    run = record_run(
        workspace=Path(args.path),
        name=args.run,
        metric_value=args.value,
        status=args.status,
        command=args.command,
        notes=args.notes,
        artifacts=args.artifact or [],
        changed_files=args.changed_file or [],
    )
    print(f"Recorded run: {run['id']}")
    print(f"Decision: {run['decision']} - {run['decision_reason']}")
    return 0


def cmd_loop_report(args: argparse.Namespace) -> int:
    state = load_loop(Path(args.path))
    report = render_report(state)
    if args.output:
        Path(args.output).write_text(report, encoding="utf-8")
        print(f"Wrote {args.output}")
    else:
        print(report)
    return 0


def cmd_loop_program(args: argparse.Namespace) -> int:
    state = load_loop(Path(args.path))
    program = render_program(state)
    target = Path(args.output) if args.output else program_path(Path(args.path))
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(program, encoding="utf-8")
    print(f"Wrote {target}")
    return 0


def cmd_improve(args: argparse.Namespace) -> int:
    failures_dir = Path(args.failures_dir).resolve() if args.failures_dir else None
    report = improvement_backlog(REPO_ROOT, failures_dir)

    if args.json_output:
        write_json(Path(args.json_output), report)
        print(f"Wrote {args.json_output}")

    backlog = render_backlog(report)
    if args.output:
        Path(args.output).write_text(backlog, encoding="utf-8")
        print(f"Wrote {args.output}")
    else:
        print(backlog)
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="mlro")
    subparsers = parser.add_subparsers(dest="command", required=True)

    list_parser = subparsers.add_parser("list-skills", help="List available ML research skills")
    list_parser.set_defaults(func=cmd_list_skills)

    init_parser = subparsers.add_parser("init", help="Initialize a research workspace")
    init_parser.add_argument("path", nargs="?", default="ml-researcher-workspace")
    init_parser.add_argument("--skills", nargs="*", help="Optional skill names to install")
    init_parser.set_defaults(func=cmd_init)

    extract_parser = subparsers.add_parser("extract-claims", help="Extract a first-pass claim brief from text")
    extract_parser.add_argument("input", help="Markdown or text file")
    extract_parser.add_argument("--output", "-o", help="Write output to a file")
    extract_parser.set_defaults(func=cmd_extract_claims)

    audit_parser = subparsers.add_parser("audit", help="Audit the skill pack for self-improvement readiness")
    audit_parser.add_argument("--json", action="store_true", help="Print machine-readable audit JSON")
    audit_parser.set_defaults(func=cmd_audit)

    doctor_parser = subparsers.add_parser("doctor", help="Score an ML repo for reproducibility readiness")
    doctor_parser.add_argument("path", nargs="?", default=".", help="Repository or workspace to inspect")
    doctor_parser.add_argument("--json", action="store_true", help="Print machine-readable doctor JSON")
    doctor_parser.add_argument("--json-output", help="Write machine-readable report JSON")
    doctor_parser.add_argument("--output", "-o", help="Write markdown report")
    doctor_parser.add_argument("--min-score", type=int, default=0, help="Exit non-zero when score is below this value")
    doctor_parser.set_defaults(func=cmd_doctor)

    failure_parser = subparsers.add_parser("record-failure", help="Record a failure case for future skill improvement")
    failure_parser.add_argument("--title", required=True)
    failure_parser.add_argument("--observed", required=True)
    failure_parser.add_argument("--expected", required=True)
    failure_parser.add_argument("--skill", required=True)
    failure_parser.add_argument("--severity", choices=["blocker", "high", "medium", "low"], default="medium")
    failure_parser.add_argument("--tag", action="append", help="Repeatable failure tag")
    failure_parser.add_argument("--evidence", default="not provided")
    failure_parser.set_defaults(func=cmd_record_failure)

    issue_parser = subparsers.add_parser("issue-from-failure", help="Render a GitHub issue body from a failure JSON file")
    issue_parser.add_argument("--failure", required=True, help="Failure JSON file")
    issue_parser.add_argument("--output", "-o", help="Write issue markdown")
    issue_parser.set_defaults(func=cmd_issue_from_failure)

    regression_parser = subparsers.add_parser("make-regression", help="Turn a failure JSON file into a regression task")
    regression_parser.add_argument("--failure", required=True, help="Failure JSON file")
    regression_parser.add_argument("--output-dir", default="benchmarks/regressions", help="Regression task root directory")
    regression_parser.add_argument("--force", action="store_true", help="Overwrite an existing task skeleton")
    regression_parser.set_defaults(func=cmd_make_regression)

    loop_parser = subparsers.add_parser("loop", help="Run a fixed-budget metric loop for agentic ML experiments")
    loop_subparsers = loop_parser.add_subparsers(dest="loop_command", required=True)

    loop_init_parser = loop_subparsers.add_parser("init", help="Initialize a research loop ledger")
    loop_init_parser.add_argument("path", nargs="?", default=".", help="Workspace to initialize")
    loop_init_parser.add_argument("--metric", required=True, help="Metric to optimize, for example val_loss")
    loop_init_parser.add_argument("--direction", choices=["lower", "higher"], default="lower")
    loop_init_parser.add_argument("--budget-minutes", type=float, default=5.0)
    loop_init_parser.add_argument("--goal", default="Improve the target metric with reproducible experiments.")
    loop_init_parser.add_argument("--command", default="not specified", help="Default command for each run")
    loop_init_parser.add_argument("--force", action="store_true", help="Overwrite an existing loop skeleton")
    loop_init_parser.set_defaults(func=cmd_loop_init)

    loop_record_parser = loop_subparsers.add_parser("record", help="Record a loop run and keep/reject by metric")
    loop_record_parser.add_argument("path", nargs="?", default=".", help="Workspace containing .mlro/research-loop.json")
    loop_record_parser.add_argument("--run", required=True, help="Human-readable run name")
    loop_record_parser.add_argument("--value", type=float, required=True, help="Observed metric value")
    loop_record_parser.add_argument("--status", choices=["completed", "failed", "skipped"], default="completed")
    loop_record_parser.add_argument("--command", help="Command used for this run")
    loop_record_parser.add_argument("--notes", default="")
    loop_record_parser.add_argument("--artifact", action="append", help="Repeatable artifact path or URL")
    loop_record_parser.add_argument("--changed-file", action="append", help="Repeatable changed file path")
    loop_record_parser.set_defaults(func=cmd_loop_record)

    loop_report_parser = loop_subparsers.add_parser("report", help="Render the research loop report")
    loop_report_parser.add_argument("path", nargs="?", default=".", help="Workspace containing .mlro/research-loop.json")
    loop_report_parser.add_argument("--output", "-o", help="Write report markdown")
    loop_report_parser.set_defaults(func=cmd_loop_report)

    loop_program_parser = loop_subparsers.add_parser("program", help="Render the agent program for this loop")
    loop_program_parser.add_argument("path", nargs="?", default=".", help="Workspace containing .mlro/research-loop.json")
    loop_program_parser.add_argument("--output", "-o", help="Write program markdown")
    loop_program_parser.set_defaults(func=cmd_loop_program)

    improve_parser = subparsers.add_parser("improve", help="Generate an improvement backlog from recorded failures")
    improve_parser.add_argument("--failures-dir", help="Directory containing failure JSON files")
    improve_parser.add_argument("--output", "-o", help="Write backlog markdown")
    improve_parser.add_argument("--json-output", help="Write machine-readable report JSON")
    improve_parser.set_defaults(func=cmd_improve)

    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
